name: Deploy to Firebase Beta Hosting on merge
'on':
  push:
    branches-ignore:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE_E466B }}'
          channelId: beta
          projectId: base-e466b
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks